stages:
  - build
  - test
  - deploy

# Stage de Build
build:
  stage: build
  script:
    - echo "Building the Docker image..."
    - docker build -t my-app:$CI_COMMIT_SHA .

# Stage de Testes
test:
  stage: test
  script:
    - echo "Running tests..."
    - docker run -e TOKEN=$TOKEN -e PREFIX=$PREFIX my-app:$CI_COMMIT_SHA pytest

# Stage de Deploy
deploy:
  stage: deploy
  script:
    - echo "Deploying to Kubernetes..."
    - kubectl apply -f k8s/deployment.yaml --namespace=my-app
  environment:
    name: production
  only:
    - main

# Cache e Artefatos
cache:
  paths:
    - .cache/pip
