apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: my-app
spec:
  replicas: 3  # Você pode ajustar conforme necessário para o número de shards
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: my-app:$CI_COMMIT_SHA  # Certifique-se de que a imagem está sendo construída corretamente
        env:
          - name: TOKEN
            value: "$TOKEN_BOT"  # Usa a variável do CI/CD diretamente
          - name: PREFIX
            value: "$PREFIX_BOT"  # Usa a variável do CI/CD diretamente
        ports:
          - containerPort: 80  # Se for realmente necessário expor alguma porta
