apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: medero/my-app:$CI_COMMIT_SHA  # Variável será substituída no CI/CD
        env:
          - name: TOKEN
            value: "$TOKEN_BOT"
          - name: PREFIX
            value: "$PREFIX_BOT"
        ports:
          - containerPort: 80
