apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      containers:
      - name: discord-bot
        image: $DOCKER_USER/my-app:$CI_COMMIT_SHA  # Usando a variável de commit SHA
        imagePullPolicy: Always  # Garante que a imagem mais recente será puxada
        envFrom:
        - configMapRef:
            name: discord-bot-env
        volumeMounts:
        - name: env-volume
          mountPath: /app/.env
          subPath: .env
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
      volumes:
      - name: env-volume
        configMap:
          name: discord-bot-env
          items:
          - key: TOKEN_BOT
            path: .env
          - key: PREFIX_BOT
            path: .env
      imagePullSecrets:
      - name: regcred
