apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: medero/my-app:$CI_COMMIT_SHA  # Variável será substituída no CI/CD
        env:
        - name: TOKEN_BOT
          valueFrom:
            secretKeyRef:
              name: my-app-secrets
              key: TOKEN_BOT
        - name: PREFIX_BOT
          valueFrom:
            secretKeyRef:
              name: my-app-secrets
              key: PREFIX_BOT
